<?php

namespace Database\Factories;

use App\Models\Stock;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Stock>
 */
class StockFactory extends Factory
{
    protected $model = Stock::class;

    public function definition(): array
    {
        return [
            // id (ULID) is auto-generated by the HasUlids trait on the Stock model.
            'stock_product_unit_id' => StockProductUnitFactory::new(),
            'expired_date'          => null,
            'is_tempel'             => true,
        ];
    }
}
